# Generated by Django 3.2.9 on 2021-11-11 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
